<?php

namespace Database\Seeders;

use App\Models\FeeInvoice;
use App\Models\SchoolClass;
use App\Models\Student;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Permissions
        $permissions = [
            'show student', 'create student', 'edit student', 'delete student', 'print student',
            'show teacher', 'create teacher', 'edit teacher', 'delete teacher', 'print teacher',
            'show accountant', 'create fee', 'edit fee', 'delete fee', 'print fee',
            'show class', 'create class', 'edit class', 'delete class', 'print class',
            'show admin',
            'see roles', 'create roles', 'edit roles', 'delete roles',
            'see permissions', 'create permissions', 'edit permissions', 'delete permissions',
            'see users', 'create users', 'edit users', 'delete users',
        ];

        foreach ($permissions as $perm) {
            Permission::firstOrCreate(['name' => $perm, 'guard_name' => 'web']);
        }

        // 2. Roles
        $adminRole = Role::firstOrCreate(['name' => 'admin', 'guard_name' => 'web']);
        $teacherRole = Role::firstOrCreate(['name' => 'teacher', 'guard_name' => 'web']);
        $accountantRole = Role::firstOrCreate(['name' => 'accountant', 'guard_name' => 'web']);
        $studentRole = Role::firstOrCreate(['name' => 'student', 'guard_name' => 'web']);

        // Admin gets all permissions
        $adminRole->syncPermissions(Permission::all());

        // Teacher permissions
        $teacherRole->syncPermissions([
            'show student', 'print student',
            'show teacher', 'print teacher',
            'show class', 'print class',
        ]);

        // Accountant permissions
        $accountantRole->syncPermissions([
            'show accountant', 'create fee', 'edit fee', 'delete fee', 'print fee',
            'show student', 'print student',
            'show class',
        ]);

        // Student permissions
        $studentRole->syncPermissions([
            'show student', 'print student',
        ]);

        // 3. Create Key Users
        $adminUser = User::firstOrCreate(
            ['email' => 'admin@school.com'],
            ['name' => 'System Admin', 'password' => Hash::make('password')]
        );
        $adminUser->syncRoles([$adminRole]);

        $teacherUser = User::firstOrCreate(
            ['email' => 'teacher@school.com'],
            ['name' => 'Prof. Sarah Jenkins', 'password' => Hash::make('password')]
        );
        $teacherUser->syncRoles([$teacherRole]);

        $accountantUser = User::firstOrCreate(
            ['email' => 'accountant@school.com'],
            ['name' => 'Alex Turner (Finance)', 'password' => Hash::make('password')]
        );
        $accountantUser->syncRoles([$accountantRole]);

        $studentUser = User::firstOrCreate(
            ['email' => 'student@school.com'],
            ['name' => 'Liam Anderson', 'password' => Hash::make('password')]
        );
        $studentUser->syncRoles([$studentRole]);

        // 4. Create Teachers
        $teachersData = [
            [
                'user_id' => $teacherUser->id,
                'employee_code' => 'TCH-1001',
                'name' => 'Prof. Sarah Jenkins',
                'email' => 'teacher@school.com',
                'phone' => '+1 (555) 234-5678',
                'qualification' => 'M.Sc. Mathematics',
                'specialization' => 'Mathematics & Statistics',
                'salary' => 4500.00,
                'joining_date' => '2021-08-15',
                'status' => 'active',
                'address' => '742 Evergreen Terrace, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1002',
                'name' => 'Dr. David Miller',
                'email' => 'david.miller@school.com',
                'phone' => '+1 (555) 345-6789',
                'qualification' => 'Ph.D. Physics',
                'specialization' => 'Physics & Chemistry',
                'salary' => 5200.00,
                'joining_date' => '2020-01-10',
                'status' => 'active',
                'address' => '12 Elm Street, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1003',
                'name' => 'Ms. Elena Rostova',
                'email' => 'elena.rostova@school.com',
                'phone' => '+1 (555) 456-7890',
                'qualification' => 'M.A. English Literature',
                'specialization' => 'English & World Literature',
                'salary' => 4200.00,
                'joining_date' => '2022-09-01',
                'status' => 'active',
                'address' => '88 Oak Avenue, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1004',
                'name' => 'Mr. Marcus Vance',
                'email' => 'marcus.vance@school.com',
                'phone' => '+1 (555) 567-8901',
                'qualification' => 'B.S. Computer Engineering',
                'specialization' => 'Computer Science & Robotics',
                'salary' => 4800.00,
                'joining_date' => '2023-02-15',
                'status' => 'active',
                'address' => '304 Maple Drive, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1005',
                'name' => 'Mrs. Farida Khan',
                'email' => 'farida.khan@school.com',
                'phone' => '+1 (555) 678-9012',
                'qualification' => 'M.Sc. Biology',
                'specialization' => 'Life Sciences & Botany',
                'salary' => 4400.00,
                'joining_date' => '2021-03-01',
                'status' => 'active',
                'address' => '19 Rose Garden, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1006',
                'name' => 'Mr. Tariq Mahmood',
                'email' => 'tariq.mahmood@school.com',
                'phone' => '+1 (555) 789-0128',
                'qualification' => 'M.A. Urdu & Islamic Studies',
                'specialization' => 'Urdu & Cultural Literature',
                'salary' => 4100.00,
                'joining_date' => '2022-01-15',
                'status' => 'active',
                'address' => '72 Jasmine Boulevard, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1007',
                'name' => 'Ms. Rachel Adams',
                'email' => 'rachel.adams@school.com',
                'phone' => '+1 (555) 890-1239',
                'qualification' => 'B.Ed. Elementary Education',
                'specialization' => 'Social Studies & Arts',
                'salary' => 3900.00,
                'joining_date' => '2023-08-01',
                'status' => 'active',
                'address' => '115 Daisy Street, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1008',
                'name' => 'Mr. Bilal Ahmed',
                'email' => 'bilal.ahmed@school.com',
                'phone' => '+1 (555) 901-2340',
                'qualification' => 'B.S. General Science',
                'specialization' => 'General Science & Physical Ed',
                'salary' => 4000.00,
                'joining_date' => '2022-11-20',
                'status' => 'active',
                'address' => '50 Palm Lane, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1009',
                'name' => 'Mrs. Grace Hopper',
                'email' => 'grace.hopper@school.com',
                'phone' => '+1 (555) 012-3451',
                'qualification' => 'M.Ed. Early Childhood',
                'specialization' => 'Junior Wing Coordinator',
                'salary' => 4700.00,
                'joining_date' => '2019-09-01',
                'status' => 'active',
                'address' => '84 Willow Way, Springfield',
            ],
            [
                'user_id' => null,
                'employee_code' => 'TCH-1010',
                'name' => 'Mr. Alan Turing',
                'email' => 'alan.turing@school.com',
                'phone' => '+1 (555) 123-4562',
                'qualification' => 'Ph.D. Applied Mathematics',
                'specialization' => 'Senior Mathematics & Computing',
                'salary' => 5400.00,
                'joining_date' => '2018-07-15',
                'status' => 'active',
                'address' => '14 Oxford Court, Springfield',
            ],
        ];

        $teachers = [];
        foreach ($teachersData as $t) {
            $teachers[] = Teacher::firstOrCreate(['employee_code' => $t['employee_code']], $t);
        }

        // 5. Create School Classes (Complete Grade 1 to Grade 12 System)
        $classesData = [
            ['name' => 'Grade 1', 'section' => 'A', 'room_number' => 'Room 101', 'capacity' => 30, 'teacher_id' => $teachers[6]->id],
            ['name' => 'Grade 2', 'section' => 'A', 'room_number' => 'Room 102', 'capacity' => 30, 'teacher_id' => $teachers[7]->id],
            ['name' => 'Grade 3', 'section' => 'A', 'room_number' => 'Room 103', 'capacity' => 30, 'teacher_id' => $teachers[8]->id],
            ['name' => 'Grade 4', 'section' => 'A', 'room_number' => 'Room 104', 'capacity' => 30, 'teacher_id' => $teachers[5]->id],
            ['name' => 'Grade 5', 'section' => 'A', 'room_number' => 'Room 105', 'capacity' => 30, 'teacher_id' => $teachers[4]->id],
            ['name' => 'Grade 6', 'section' => 'A', 'room_number' => 'Room 201', 'capacity' => 35, 'teacher_id' => $teachers[0]->id],
            ['name' => 'Grade 7', 'section' => 'A', 'room_number' => 'Room 202', 'capacity' => 35, 'teacher_id' => $teachers[1]->id],
            ['name' => 'Grade 8', 'section' => 'A', 'room_number' => 'Room 203', 'capacity' => 35, 'teacher_id' => $teachers[2]->id],
            ['name' => 'Grade 8', 'section' => 'B', 'room_number' => 'Room 204', 'capacity' => 35, 'teacher_id' => $teachers[3]->id],
            ['name' => 'Grade 9', 'section' => 'A', 'room_number' => 'Room 301', 'capacity' => 35, 'teacher_id' => $teachers[0]->id],
            ['name' => 'Grade 9', 'section' => 'B', 'room_number' => 'Room 302', 'capacity' => 35, 'teacher_id' => $teachers[1]->id],
            ['name' => 'Grade 10', 'section' => 'A', 'room_number' => 'Room 303', 'capacity' => 30, 'teacher_id' => $teachers[2]->id],
            ['name' => 'Grade 10', 'section' => 'B', 'room_number' => 'Room 304', 'capacity' => 30, 'teacher_id' => $teachers[3]->id],
            ['name' => 'Grade 11', 'section' => 'A', 'room_number' => 'Room 401', 'capacity' => 40, 'teacher_id' => $teachers[9]->id],
            ['name' => 'Grade 12', 'section' => 'A', 'room_number' => 'Room 402', 'capacity' => 40, 'teacher_id' => $teachers[9]->id],
        ];

        $classesMap = [];
        foreach ($classesData as $c) {
            $classModel = SchoolClass::firstOrCreate(
                ['name' => $c['name'], 'section' => $c['section']],
                $c
            );
            $classesMap[$c['name'].'-'.$c['section']] = $classModel;
        }

        // 6. Create Students Enrolled in Classes
        $studentsData = [
            // Grade 1 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 1-A',
                'admission_number' => 'ADM-2024-101',
                'roll_number' => '01A-01',
                'name' => 'Zayn Malik',
                'email' => 'zayn.m@example.com',
                'phone' => '+1 (555) 789-1001',
                'gender' => 'male',
                'date_of_birth' => '2018-05-12',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Tariq Malik',
                'guardian_phone' => '+1 (555) 890-1001',
                'guardian_relation' => 'Father',
                'address' => '12 Rosewood Lane, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 1-A',
                'admission_number' => 'ADM-2024-102',
                'roll_number' => '01A-02',
                'name' => 'Fatima Noor',
                'email' => 'fatima.n@example.com',
                'phone' => '+1 (555) 789-1002',
                'gender' => 'female',
                'date_of_birth' => '2018-09-20',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Naveed Noor',
                'guardian_phone' => '+1 (555) 890-1002',
                'guardian_relation' => 'Father',
                'address' => '44 Sunset Street, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 1-A',
                'admission_number' => 'ADM-2024-103',
                'roll_number' => '01A-03',
                'name' => 'Arham Sheikh',
                'email' => 'arham.s@example.com',
                'phone' => '+1 (555) 789-1003',
                'gender' => 'male',
                'date_of_birth' => '2018-02-15',
                'admission_date' => '2024-08-05',
                'guardian_name' => 'Khurram Sheikh',
                'guardian_phone' => '+1 (555) 890-1003',
                'guardian_relation' => 'Father',
                'address' => '88 Blossom Court, Springfield',
                'status' => 'active',
            ],
            // Grade 2 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 2-A',
                'admission_number' => 'ADM-2024-104',
                'roll_number' => '02A-01',
                'name' => 'Ayan Qureshi',
                'email' => 'ayan.q@example.com',
                'phone' => '+1 (555) 789-1004',
                'gender' => 'male',
                'date_of_birth' => '2017-06-11',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Babar Qureshi',
                'guardian_phone' => '+1 (555) 890-1004',
                'guardian_relation' => 'Father',
                'address' => '21 Jasmine Court, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 2-A',
                'admission_number' => 'ADM-2024-105',
                'roll_number' => '02A-02',
                'name' => 'Maryam Bibi',
                'email' => 'maryam.b@example.com',
                'phone' => '+1 (555) 789-1005',
                'gender' => 'female',
                'date_of_birth' => '2017-08-14',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Amjad Ali',
                'guardian_phone' => '+1 (555) 890-1005',
                'guardian_relation' => 'Father',
                'address' => '95 Daisy Avenue, Springfield',
                'status' => 'active',
            ],
            // Grade 3 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 3-A',
                'admission_number' => 'ADM-2024-106',
                'roll_number' => '03A-01',
                'name' => 'Hamza Ali',
                'email' => 'hamza.a@example.com',
                'phone' => '+1 (555) 789-1006',
                'gender' => 'male',
                'date_of_birth' => '2016-04-18',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Akram Ali',
                'guardian_phone' => '+1 (555) 890-1006',
                'guardian_relation' => 'Father',
                'address' => '101 Pine Ridge, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 3-A',
                'admission_number' => 'ADM-2024-107',
                'roll_number' => '03A-02',
                'name' => 'Anaya Tariq',
                'email' => 'anaya.t@example.com',
                'phone' => '+1 (555) 789-1007',
                'gender' => 'female',
                'date_of_birth' => '2016-10-09',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Tariq Javed',
                'guardian_phone' => '+1 (555) 890-1007',
                'guardian_relation' => 'Father',
                'address' => '67 Maple Boulevard, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 3-A',
                'admission_number' => 'ADM-2024-108',
                'roll_number' => '03A-03',
                'name' => 'Bilal Shah',
                'email' => 'bilal.s@example.com',
                'phone' => '+1 (555) 789-1008',
                'gender' => 'male',
                'date_of_birth' => '2016-01-25',
                'admission_date' => '2024-08-10',
                'guardian_name' => 'Zulfiqar Shah',
                'guardian_phone' => '+1 (555) 890-1008',
                'guardian_relation' => 'Father',
                'address' => '32 Lakeview Drive, Springfield',
                'status' => 'active',
            ],
            // Grade 4 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 4-A',
                'admission_number' => 'ADM-2024-109',
                'roll_number' => '04A-01',
                'name' => 'Daniyal Khan',
                'email' => 'daniyal.k@example.com',
                'phone' => '+1 (555) 789-1009',
                'gender' => 'male',
                'date_of_birth' => '2015-03-30',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Junaid Khan',
                'guardian_phone' => '+1 (555) 890-1009',
                'guardian_relation' => 'Father',
                'address' => '14 Orchard Way, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 4-A',
                'admission_number' => 'ADM-2024-110',
                'roll_number' => '04A-02',
                'name' => 'Hania Amir',
                'email' => 'hania.a@example.com',
                'phone' => '+1 (555) 789-1010',
                'gender' => 'female',
                'date_of_birth' => '2015-07-14',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Amir Sohail',
                'guardian_phone' => '+1 (555) 890-1010',
                'guardian_relation' => 'Father',
                'address' => '83 Cedar Court, Springfield',
                'status' => 'active',
            ],
            // Grade 5 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 5-A',
                'admission_number' => 'ADM-2024-111',
                'roll_number' => '05A-01',
                'name' => 'Saad Rehan',
                'email' => 'saad.r@example.com',
                'phone' => '+1 (555) 789-1011',
                'gender' => 'male',
                'date_of_birth' => '2014-02-17',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Rehan Siddiq',
                'guardian_phone' => '+1 (555) 890-1011',
                'guardian_relation' => 'Father',
                'address' => '55 Spring Street, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 5-A',
                'admission_number' => 'ADM-2024-112',
                'roll_number' => '05A-02',
                'name' => 'Sara Ahmed',
                'email' => 'sara.ahmed@example.com',
                'phone' => '+1 (555) 789-1012',
                'gender' => 'female',
                'date_of_birth' => '2014-08-22',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Ahmed Rauf',
                'guardian_phone' => '+1 (555) 890-1012',
                'guardian_relation' => 'Father',
                'address' => '76 Elmwood Road, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 5-A',
                'admission_number' => 'ADM-2024-113',
                'roll_number' => '05A-03',
                'name' => 'Usman Ghani',
                'email' => 'usman.g@example.com',
                'phone' => '+1 (555) 789-1013',
                'gender' => 'male',
                'date_of_birth' => '2014-11-05',
                'admission_date' => '2024-08-15',
                'guardian_name' => 'Ghani Rehman',
                'guardian_phone' => '+1 (555) 890-1013',
                'guardian_relation' => 'Father',
                'address' => '90 Hillview Drive, Springfield',
                'status' => 'active',
            ],
            // Grade 6 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 6-A',
                'admission_number' => 'ADM-2024-114',
                'roll_number' => '06A-01',
                'name' => 'Ibrahim Khalil',
                'email' => 'ibrahim.k@example.com',
                'phone' => '+1 (555) 789-1014',
                'gender' => 'male',
                'date_of_birth' => '2013-03-19',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Khalil Ahmed',
                'guardian_phone' => '+1 (555) 890-1014',
                'guardian_relation' => 'Father',
                'address' => '11 Valley Road, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 6-A',
                'admission_number' => 'ADM-2024-115',
                'roll_number' => '06A-02',
                'name' => 'Zoya Hassan',
                'email' => 'zoya.h@example.com',
                'phone' => '+1 (555) 789-1015',
                'gender' => 'female',
                'date_of_birth' => '2013-09-12',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Hassan Raza',
                'guardian_phone' => '+1 (555) 890-1015',
                'guardian_relation' => 'Father',
                'address' => '28 Gardenia Lane, Springfield',
                'status' => 'active',
            ],
            // Grade 7 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 7-A',
                'admission_number' => 'ADM-2024-116',
                'roll_number' => '07A-01',
                'name' => 'Rayan Siddiqui',
                'email' => 'rayan.s@example.com',
                'phone' => '+1 (555) 789-1016',
                'gender' => 'male',
                'date_of_birth' => '2012-05-24',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Noman Siddiqui',
                'guardian_phone' => '+1 (555) 890-1016',
                'guardian_relation' => 'Father',
                'address' => '39 Heights Terrace, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 7-A',
                'admission_number' => 'ADM-2024-117',
                'roll_number' => '07A-02',
                'name' => 'Ayesha Nadeem',
                'email' => 'ayesha.n@example.com',
                'phone' => '+1 (555) 789-1017',
                'gender' => 'female',
                'date_of_birth' => '2012-11-30',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Nadeem Akhtar',
                'guardian_phone' => '+1 (555) 890-1017',
                'guardian_relation' => 'Father',
                'address' => '47 Riverbank Way, Springfield',
                'status' => 'active',
            ],
            // Grade 8 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 8-A',
                'admission_number' => 'ADM-2024-118',
                'roll_number' => '08A-01',
                'name' => 'Omar Farooq',
                'email' => 'omar.f@example.com',
                'phone' => '+1 (555) 789-1018',
                'gender' => 'male',
                'date_of_birth' => '2011-01-14',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Farooq Azam',
                'guardian_phone' => '+1 (555) 890-1018',
                'guardian_relation' => 'Father',
                'address' => '62 Willow Crest, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 8-A',
                'admission_number' => 'ADM-2024-119',
                'roll_number' => '08A-02',
                'name' => 'Mahnoor Fatima',
                'email' => 'mahnoor.f@example.com',
                'phone' => '+1 (555) 789-1019',
                'gender' => 'female',
                'date_of_birth' => '2011-06-28',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Sohail Aslam',
                'guardian_phone' => '+1 (555) 890-1019',
                'guardian_relation' => 'Father',
                'address' => '71 Oakridge Plaza, Springfield',
                'status' => 'active',
            ],
            // Grade 8 - B
            [
                'user_id' => null,
                'class_key' => 'Grade 8-B',
                'admission_number' => 'ADM-2024-120',
                'roll_number' => '08B-01',
                'name' => 'Mustafa Kamal',
                'email' => 'mustafa.k@example.com',
                'phone' => '+1 (555) 789-1020',
                'gender' => 'male',
                'date_of_birth' => '2011-08-03',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Kamal Pasha',
                'guardian_phone' => '+1 (555) 890-1020',
                'guardian_relation' => 'Father',
                'address' => '100 Crescent Road, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 8-B',
                'admission_number' => 'ADM-2024-121',
                'roll_number' => '08B-02',
                'name' => 'Zainab Bibi',
                'email' => 'zainab.b@example.com',
                'phone' => '+1 (555) 789-1021',
                'gender' => 'female',
                'date_of_birth' => '2011-12-16',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Rashid Mehmood',
                'guardian_phone' => '+1 (555) 890-1021',
                'guardian_relation' => 'Father',
                'address' => '18 Cedar Hills, Springfield',
                'status' => 'active',
            ],
            // Grade 9 - A
            [
                'user_id' => $studentUser->id,
                'class_key' => 'Grade 9-A',
                'admission_number' => 'ADM-2024-001',
                'roll_number' => '09A-01',
                'name' => 'Liam Anderson',
                'email' => 'student@school.com',
                'phone' => '+1 (555) 789-0123',
                'gender' => 'male',
                'date_of_birth' => '2009-04-12',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Robert Anderson',
                'guardian_phone' => '+1 (555) 890-1234',
                'guardian_relation' => 'Father',
                'address' => '45 Hilltop Way, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 9-A',
                'admission_number' => 'ADM-2024-002',
                'roll_number' => '09A-02',
                'name' => 'Sophia Martinez',
                'email' => 'sophia.m@example.com',
                'phone' => '+1 (555) 789-0124',
                'gender' => 'female',
                'date_of_birth' => '2009-07-22',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Maria Martinez',
                'guardian_phone' => '+1 (555) 890-1235',
                'guardian_relation' => 'Mother',
                'address' => '102 Sunset Blvd, Springfield',
                'status' => 'active',
            ],
            // Grade 9 - B
            [
                'user_id' => null,
                'class_key' => 'Grade 9-B',
                'admission_number' => 'ADM-2024-003',
                'roll_number' => '09B-01',
                'name' => 'Ethan Walker',
                'email' => 'ethan.w@example.com',
                'phone' => '+1 (555) 789-0125',
                'gender' => 'male',
                'date_of_birth' => '2009-02-18',
                'admission_date' => '2024-08-05',
                'guardian_name' => 'James Walker',
                'guardian_phone' => '+1 (555) 890-1236',
                'guardian_relation' => 'Father',
                'address' => '54 Meadow Lane, Springfield',
                'status' => 'active',
            ],
            // Grade 10 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 10-A',
                'admission_number' => 'ADM-2023-015',
                'roll_number' => '10A-01',
                'name' => 'Olivia Taylor',
                'email' => 'olivia.t@example.com',
                'phone' => '+1 (555) 789-0126',
                'gender' => 'female',
                'date_of_birth' => '2008-11-05',
                'admission_date' => '2023-08-10',
                'guardian_name' => 'George Taylor',
                'guardian_phone' => '+1 (555) 890-1237',
                'guardian_relation' => 'Father',
                'address' => '22 River Road, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 10-A',
                'admission_number' => 'ADM-2023-028',
                'roll_number' => '10A-02',
                'name' => 'Ava Wilson',
                'email' => 'ava.w@example.com',
                'phone' => '+1 (555) 789-0128',
                'gender' => 'female',
                'date_of_birth' => '2008-05-14',
                'admission_date' => '2023-08-15',
                'guardian_name' => 'Arthur Wilson',
                'guardian_phone' => '+1 (555) 890-1239',
                'guardian_relation' => 'Father',
                'address' => '31 Cedar Court, Springfield',
                'status' => 'active',
            ],
            // Grade 10 - B
            [
                'user_id' => null,
                'class_key' => 'Grade 10-B',
                'admission_number' => 'ADM-2023-022',
                'roll_number' => '10B-01',
                'name' => 'Noah Chen',
                'email' => 'noah.c@example.com',
                'phone' => '+1 (555) 789-0127',
                'gender' => 'male',
                'date_of_birth' => '2008-09-30',
                'admission_date' => '2023-08-12',
                'guardian_name' => 'Linda Chen',
                'guardian_phone' => '+1 (555) 890-1238',
                'guardian_relation' => 'Mother',
                'address' => '89 Pine Grove, Springfield',
                'status' => 'active',
            ],
            // Grade 11 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 11-A',
                'admission_number' => 'ADM-2024-122',
                'roll_number' => '11A-01',
                'name' => 'Ahsan Raza',
                'email' => 'ahsan.r@example.com',
                'phone' => '+1 (555) 789-1022',
                'gender' => 'male',
                'date_of_birth' => '2007-03-12',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Raza Qasim',
                'guardian_phone' => '+1 (555) 890-1022',
                'guardian_relation' => 'Father',
                'address' => '15 Elite Villas, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 11-A',
                'admission_number' => 'ADM-2024-123',
                'roll_number' => '11A-02',
                'name' => 'Dua Zahra',
                'email' => 'dua.z@example.com',
                'phone' => '+1 (555) 789-1023',
                'gender' => 'female',
                'date_of_birth' => '2007-09-29',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Syed Abbas',
                'guardian_phone' => '+1 (555) 890-1023',
                'guardian_relation' => 'Father',
                'address' => '29 Capital View, Springfield',
                'status' => 'active',
            ],
            // Grade 12 - A
            [
                'user_id' => null,
                'class_key' => 'Grade 12-A',
                'admission_number' => 'ADM-2024-124',
                'roll_number' => '12A-01',
                'name' => 'Hassan Abbas',
                'email' => 'hassan.ab@example.com',
                'phone' => '+1 (555) 789-1024',
                'gender' => 'male',
                'date_of_birth' => '2006-04-10',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Abbas Haider',
                'guardian_phone' => '+1 (555) 890-1024',
                'guardian_relation' => 'Father',
                'address' => '51 Grand Avenue, Springfield',
                'status' => 'active',
            ],
            [
                'user_id' => null,
                'class_key' => 'Grade 12-A',
                'admission_number' => 'ADM-2024-125',
                'roll_number' => '12A-02',
                'name' => 'Emaan Faisal',
                'email' => 'emaan.f@example.com',
                'phone' => '+1 (555) 789-1025',
                'gender' => 'female',
                'date_of_birth' => '2006-11-15',
                'admission_date' => '2024-08-01',
                'guardian_name' => 'Faisal Munir',
                'guardian_phone' => '+1 (555) 890-1025',
                'guardian_relation' => 'Father',
                'address' => '73 University Road, Springfield',
                'status' => 'active',
            ],
        ];

        $students = [];
        foreach ($studentsData as $s) {
            $classKey = $s['class_key'];
            unset($s['class_key']);
            $s['school_class_id'] = $classesMap[$classKey]->id ?? null;

            $students[] = Student::firstOrCreate(['admission_number' => $s['admission_number']], $s);
        }

        // 7. Create Fee Invoices
        $invoicesData = [
            [
                'student_id' => $students[0]->id,
                'created_by' => $accountantUser->id,
                'invoice_number' => 'INV-2026-001',
                'title' => 'Tuition Fee - October 2026',
                'fee_type' => 'tuition',
                'total_amount' => 450.00,
                'paid_amount' => 450.00,
                'due_date' => '2026-10-10',
                'paid_date' => '2026-10-05',
                'status' => 'paid',
                'payment_method' => 'bank_transfer',
                'notes' => 'Paid in full via online bank transfer.',
            ],
            [
                'student_id' => $students[1]->id,
                'created_by' => $accountantUser->id,
                'invoice_number' => 'INV-2026-002',
                'title' => 'Tuition Fee - October 2026',
                'fee_type' => 'tuition',
                'total_amount' => 450.00,
                'paid_amount' => 200.00,
                'due_date' => '2026-10-10',
                'paid_date' => '2026-10-08',
                'status' => 'partial',
                'payment_method' => 'cash',
                'notes' => 'Partial cash payment received. Balance due before end of month.',
            ],
            [
                'student_id' => $students[2]->id,
                'created_by' => $accountantUser->id,
                'invoice_number' => 'INV-2026-003',
                'title' => 'Tuition Fee - October 2026',
                'fee_type' => 'tuition',
                'total_amount' => 450.00,
                'paid_amount' => 0.00,
                'due_date' => '2026-10-15',
                'paid_date' => null,
                'status' => 'unpaid',
                'payment_method' => null,
                'notes' => 'Pending payment.',
            ],
            [
                'student_id' => $students[3]->id,
                'created_by' => $accountantUser->id,
                'invoice_number' => 'INV-2026-004',
                'title' => 'Annual Exam Fee - 2026',
                'fee_type' => 'exam',
                'total_amount' => 150.00,
                'paid_amount' => 150.00,
                'due_date' => '2026-10-01',
                'paid_date' => '2026-09-28',
                'status' => 'paid',
                'payment_method' => 'online',
                'notes' => 'Paid via debit card.',
            ],
            [
                'student_id' => $students[4]->id,
                'created_by' => $accountantUser->id,
                'invoice_number' => 'INV-2026-005',
                'title' => 'Tuition & Lab Fee - October 2026',
                'fee_type' => 'tuition',
                'total_amount' => 520.00,
                'paid_amount' => 520.00,
                'due_date' => '2026-10-10',
                'paid_date' => '2026-10-02',
                'status' => 'paid',
                'payment_method' => 'cheque',
                'notes' => 'Cheque #8832 cleared successfully.',
            ],
            [
                'student_id' => $students[5]->id,
                'created_by' => $accountantUser->id,
                'invoice_number' => 'INV-2026-006',
                'title' => 'Transport Fee - Term 1',
                'fee_type' => 'transport',
                'total_amount' => 300.00,
                'paid_amount' => 0.00,
                'due_date' => '2026-10-20',
                'paid_date' => null,
                'status' => 'unpaid',
                'payment_method' => null,
                'notes' => 'First installment due.',
            ],
        ];

        foreach ($invoicesData as $inv) {
            FeeInvoice::firstOrCreate(['invoice_number' => $inv['invoice_number']], $inv);
        }
    }
}
